name: Client Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/public-viewer/**/*.ts'
      - 'apps/public-viewer/**/*.tsx'
      - 'apps/public-viewer/**/*.js'
      - 'apps/public-viewer/**/*.jsx'
      - 'apps/public-viewer/package.json'
      - 'apps/public-viewer/jest.config.js'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/public-viewer/**/*.ts'
      - 'apps/public-viewer/**/*.tsx'
      - 'apps/public-viewer/**/*.js'
      - 'apps/public-viewer/**/*.jsx'
      - 'apps/public-viewer/package.json'
      - 'apps/public-viewer/jest.config.js'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/public-viewer

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ./apps/public-viewer/package.json

    - name: Install dependencies
      run: npm ci

    - name: Run tests with Jest
      run: npm test
